[project]
name = "concordia-web-crawler"
version = "1.0.1"
description = "An app for scraping the Concordia University website to perform sentiment analysis on the scraped documents."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "afinn>=0.1",
    "beautifulsoup4>=4.14.3",
    "nltk>=3.9.4",
    "numpy>=2.4.5",
    "scikit-learn>=1.8.0",
    "scrapy>=2.15.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.13",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "E501", # Enable line-too-long rule
    "UP",   # Enable pyupgrade rules
    "W",    # Enable pycodestyle warnings
    "C90",  # Enable McCabe complexity
    "B",    # Enable flake8-bugbear rules
    "A",    # Enable flake8-builtin rules
    "COM",  # Enable flake8-commas rules
    "C4",   # Enable flake8-comprehensions rules
    "ISC",  # Enable flake8-implicit-str-concat rules
    "ICN",  # Enable flake8-import-conventions rules
    "PIE",  # Enable flake8-pie rules
    "PT",   # Enable flake8-pytest-style rules
    "RET",  # Enable flake8-return rules
    "ARG",  # Enable flake8-unused-arguments rules
    "F",    # Enable Pyflakes rules
    "FURB", # Enable refurb rules
    "PERF", # Enable Perflint rules
    "RUF",  # Enable Ruff specific rules
    "SIM",  # Enable flake8-simplify rules
    "Q",    # Enable flake8-quotes rules
    "I",    # Enable isort rules

    # Unused rules for now:

    # "TC", # flake8-type-checking
    # "DOC", # pydoclint
    # "PL", # Pylint
]

ignore = [
    "COM812", # Ignore absence of trailing commas. Formatter handles that
]
